---

############################### Dependencies and paths #############################################

path_dir: /usr/local/bin

## GATK
GATK_install_dir: /opt/
GATK_archive_url: https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.8-1-0-gf15c1c3ef

## Picard
picard_version: 2.18.2 
picard_install_dir: /opt/picard-{{ picard_version }}
picard_archive_url: https://github.com/broadinstitute/picard/releases/download/{{ picard_version }}/picard.jar

## Samtools
samtools_version: 1.8
samtools_archive_url: https://github.com/samtools/samtools/releases/download/{{ samtools_version }}/samtools-{{ samtools_version }}.tar.bz2
samtools_install_dir: /usr/local/bin

## BWA
bwa_always_replace: False
bwa_repo: https://github.com/lh3/bwa.git

## Bowtie2
bowtie2_version: 2.3.4.1
bowtie2_archive_url: https://github.com/BenLangmead/bowtie2/releases/download/v{{ bowtie2_version }}/bowtie2-{{ bowtie2_version }}-linux-x86_64.zip
bowtie2_install_dir: /usr/local/bin

## wgsim
wgsim_always_replace: False
wgsim_repo: https://github.com/lh3/wgsim


## PHEnix
phenix_version: 1.4.1

## SnapperDB
snapperdb_version: 1.0.4
confpath: /home/centos/snapperdb-conf
refpath: /home/centos/snapperdb-ref

## PostgreSQL
postgres_version: 9.6
postgres_repo_rpm: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
postgres_centos_rpms:
  - postgresql{{ postgres_version|replace('.', '') }}
  - postgresql{{ postgres_version|replace('.', '') }}-server
  - postgresql{{ postgres_version|replace('.', '') }}-contrib


################################ PostgreSQL config ##################################################
pg_listen_addresses: localhost


################################ SnapperDB users ####################################################

pg_uname: snapperdb
