---

- name: "Create postgresql conf file"
  template:
    src: postgres/postgresql.conf.j2
    dest: "/var/lib/pgsql/{{ postgres_version }}/data/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0600
  become: yes
  register: postgresql_conf

- name: "Create postgresql pg_hba file"
  template:
    src: postgres/pg_hba.conf.j2
    dest: "/var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  become: yes
  register: pg_hba_conf

- name: "Restart postgresql on config change"
  systemd:
    state: restarted
    name: postgresql-{{ postgres_version }}
  become: yes
  when: postgresql_conf.changed or pg_hba_conf.changed 
