---

- name: "Add postgres yum repo"
  yum:
    name: "{{ postgres_repo_rpm }}"
    state: present
  become: yes

- name: "Install postgres packages"
  yum:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    "{{ postgres_centos_rpms }}"

- stat:
    path: "/var/lib/pgsql/{{ postgres_version }}/initdb.log"
  register: pginit
  become: yes

- name: "initialize postgres database"
  command: "/usr/pgsql-{{ postgres_version}}/bin/postgresql{{ postgres_version|replace('.', '') }}-setup initdb"
  become: yes
  when: pginit.stat.exists == False

- name: "Start and enable postgres service"
  systemd:
    name: postgresql-{{ postgres_version }}
    state: started
    enabled: True
  become: yes
