---

- name: "Install PHEnix deps with yum"
  yum:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
      - Cython
      - python2-matplotlib
      - python2-numpy

- name: "Install PHEnix deps with pip"
  pip:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - bintrees

- name: "Install PHEnix with pip"
  pip:
    name: PHEnix
    version: "{{ phenix_version }}"
  become: yes
